compressionLevel: 0

enableGlobalCache: true

nmHoistingLimits: none

nmMode: hardlinks-local

nodeLinker: node-modules

logFilters:
  - code: YN0066
    level: discard

packageExtensions:
  sonner@*:
    peerDependencies:
      react: "^18.0.0 || ^19.0.0"
      react-dom: "^18.0.0 || ^19.0.0"
