approvedGitRepositories:
  - "**"

compressionLevel: 0

enableGlobalCache: true

enableScripts: true

logFilters:
  - code: YN0066
    level: discard

nmHoistingLimits: none

nmMode: hardlinks-local

nodeLinker: node-modules

npmMinimalAgeGate: 0

packageExtensions:
  sonner@*:
    peerDependencies:
      react: ^18.0.0 || ^19.0.0
      react-dom: ^18.0.0 || ^19.0.0
