import { LoadingProvider } from '@/components/Loading/LoadingContext';
import { Flex, Text } from '@chakra-ui/react';
import { BRAND_COLOR } from '@guide-me-app/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <body className={inter.className} suppressHydrationWarning>
        <LoadingProvider>
            <Providers>
                <Flex flex={1} flexDirection='column'>
                    <Flex width="100%" style={{ padding: '2rem', background: BRAND_COLOR, justifyContent: 'center' }}>
                        <Text style={{ fontWeight: 'bold' }}>
                            GuideMe! admin
                        </Text>
                    </Flex>
                    {children}
                </Flex>
            </Providers>
        </LoadingProvider>
        </body>
        </html>
    );
}
