import { Header } from '@/components/Header';
import { LoadingProvider } from '@/components/Loading/LoadingContext';
import { Flex } from '@chakra-ui/react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import './globals.css';
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
        <body className={inter.className} suppressHydrationWarning>
        <LoadingProvider>
            <Providers>
                <Flex flex={1} flexDirection="column">
                    <Header/>
                    {children}
                </Flex>
            </Providers>
        </LoadingProvider>
        </body>
        </html>
    );
}
